### ISSUE TITLE
Windows: file path issue

### ISSUE THREAD

**Issue by GoGoris** [g3offrey/javascript-test-runner#7]
Hi, I am using VSCode on Windows 10 with the shell command line runner. Your plugin does look very promising, unfortunately it does not work for me because my windows paths are not correctly transformed to git bash.

It would be nice if you could implement the following fixes:
1. A setting for the path to the jest executable
2. Relative file paths with forward slashes as test parameter

**Comment by g3offrey** [comment]
Hi @GoGoris 
thank you very much for your feedback and for the issue 😄 
I will investigate on this and create a package to enable Windows user to use the extension 😉 

Sadly, I am unable to test it on a real windows machine, is it possible for you to test a package if I send one to you ? 😅

**Comment by fabiohvp** [comment]
Another problem is when the path contains spaces. for instance, my project is in a Visual Code folder, when I try to execute the plugin it gives me "d:\Projetos\Visual : The term 'd:\Projetos\Visual' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again."
This would be fixed if the path is between double quotes "".

**Comment by g3offrey** [comment]
@fabiohvp thank you very much for your contribution that's very nice of you 👍 
Yeah indeed I need to improve path management especially for Windows user. As soon as I have I have a bit more time I'll try to improve that 😅 
Thank you for pointing me out this issue 👍

**Comment by tcov189** [comment]
@g3offrey If you need someone to test out packages on a Windows machine I would be happy to help out

**Comment by GoGoris** [comment]
@g3offrey Of course! I will gladly provide feedback to you if you send me a package to test on Windows. It can take a day however before I answer because this week thursday for example I am out of office.

**Comment by g3offrey** [comment]
Thank you @GoGoris and @tcov189, that's very kind of you 😄 
I think I'll start to work on this next week. 

Don't worry if you don't have time to test it. I'll find another solution. Just enjoy your free time that's the most important.
Anyway I'll ping people in this thread when I have a nice package available for test 👍

Thank you again for your help 👌

**Comment by tcov189** [comment]
Awesome, thanks @g3offrey.

**Comment by g3offrey** [comment]
I just merged the branch containing the Windows support. 
This will be released in less than 48 hours. 
Thank you everybody for your help, I really appreciate this. 😄 

I already did some testing but if you encounter any issue don't hesitate to open a new ticket, I'll be glad to fix it as soon as possible 👌

**Comment by fallanic** [comment]
Thanks @g3offrey , are these changes included in the 1.0.0 release?

VS code is struggling to find Jest on my windows laptop when clicking on either `run test` or `debug test`🤔 

![image](https://user-images.githubusercontent.com/1240520/43222798-c6c8a030-9016-11e8-9094-841d5f8fd774.png)

(I am using 1.0.0)

Also just a suggestion, but it would be nice to add a git tag / release on Github, to know what's included in the release :) (and Github did a great job to make it easy to do 👍 ).

**Comment by roggenbrot** [comment]
The problem is that the test runner is searched in node_modules/.bin folder while on windows it's node_modules/bin

As a temp workaround you could monkey patch this be opening `%USERPROFILE%.vscode\extensions\legfrey.javascript-test-runner-1.0.0/out/runners/JestTestRunner.js` /  `%USERPROFILE%.vscode\extensions\legfrey.javascript-test-runner-1.0.0/out/runners/MockTestRunner.js`

```
    get binPath() {
        return path_1.join("node_modules", ".bin", "jest");
    }
```

to 

```
    get binPath() {
        return path_1.join("node_modules", "bin", "jest");
    }
```

**Comment by roggenbrot** [comment]
Fixed it in #24 
It would be very helpful if you could test these changes in your environment since I don't have a window installation

**Comment by tcov189** [comment]
@roggenbrot That didn't work for me. My test runner was indeed in node_modules/.bin.

**Comment by roggenbrot** [comment]
@tcov189 @fallanic  Could you try if it's working if you change `%USERPROFILE%.vscode\extensions\legfrey.javascript-test-runner-1.0.0/out/runners/TestRunnerFactory.js`


from 


```
function getAvailableTestRunner(testRunners, rootPath) {
    return __awaiter(this, void 0, void 0, function* () {
        for (const runner of testRunners) {
            const doesRunnerExist = yield doesFileExist(path_1.join(rootPath.uri.path, runner.binPath));
            if (doesRunnerExist) {
                return runner;
            }
        }
        throw new Error("No test runner in your project. Please install one.");
    });
}
```


to 

```
function getAvailableTestRunner(testRunners, rootPath) {
    return __awaiter(this, void 0, void 0, function* () {
        for (const runner of testRunners) {
            const doesRunnerExist = yield doesFileExist(path_1.join(rootPath.uri.fsPath, runner.binPath));
            if (doesRunnerExist) {
                return runner;
            }
        }
        throw new Error("No test runner in your project. Please install one.");
    });
}
```

If it's working uri.path has to be changed to uri.fsPath in all files for full windows support. Can you check if it's working and give me a feedback so that I could create a PR?

**Comment by tcov189** [comment]
@roggenbrot That got rid of the error for test runner could not be found, still not able to run tests because of spaces in file path.

**Comment by tcov189** [comment]
It appears to be adding a / to the beginning of the file path as well. This is the output I get in my terminal:
```
FIRSTNAME LASTNAME@DESKTOP MINGW64 ~/API (update/tc_api_documentation)
$ cd /c:/Users/FIRSTNAME LASTNAME/API
bash: cd: too many arguments

FIRSTNAME LASTNAME@DESKTOP MINGW64 ~/API (update/tc_api_documentation)
$ node_modules\.bin\mocha ..\..\..\..\Users\FIRSTNAME LASTNAME\API\test\main-routes.test.js --grep="main routes"
bash: node_modules.binmocha: command not found

FIRSTNAME LASTNAME@DESKTOP MINGW64 /c/Users
$


```

**Comment by g3offrey** [comment]
Thank you for your feedbacks and sorry for the inconvenience, I'll check this as soon as I merge the awesome @roggenbrot's PR (#24) 👌

**Comment by omar-zakaria** [comment]
I can confirm @tcov189 's observation. I have the same problem on two different win10 machines, with two seperate projects. 

To counter the issue, I have had to modify the extension code  while waiting for the fix. I basically added a skip to the first "/" of the mocha path
`const doesRunnerExist = yield doesFileExist(path_1.join(rootPath.uri.path, runner.binPath).substring(1));`
TestRunnerFactory file


I don't know if that helps in any way.  I really enjoy your extension as I find it a lot easier to use than other mocha test runners with my configuration.
Thanks!

**Comment by nhanledev** [comment]
I also have problem when using this runner with VSCODE and WSL.

The script detected my `rootPath.uri.path` as `/c:/projects/api-gateway` when the real path that node can execute the jest runner must be `/mnt/c/projects/api-gateway`

I think the extension should provide a way to config the environment i,e windows, linux, mac or wsl or it will auto detect the environment when config was not provided.

Currently I have to edit the plugin for replacing the path `rootPath.uri.path.replace('c:', 'mnt/c')`

**Comment by LoveSponge** [comment]
@tcov189
Untested (except my own machine) fix:
As @roggenbrot updated `uri.path` to be `uri.fsPath` in `[mocha/jest]TestRunner.js`.
You must update it everywhere, most notably (for me it fixed command line error) in:
`${ROOT_OF_EXT}/out/providers/TerminalProvider.js:13:57`

I also changed in:
`${ROOT_OF_EXT}/out/runners/TestRunnerFactory:28:82`

**Comment by tcov189** [comment]
@LoveSponge I will try this out, thanks.

EDIT: I just tried it, still no dice. cd has too many arguments error again.

**Comment by tcov189** [comment]
I think I have a better idea of whats going on. So the problem that I am having is that backslashes are being interpreted as escape characters in the bash integrated terminal.  I confirmed this by changing my default terminal to PowerShell, and it worked just fine.

Edit: I finally got it to work by putting quotes around where a command was being piped into a terminal. 
```${ROOT_OF_EXT}/out/runners/MochaTestRunner.js:20:26``` around both ```${this.binPath}``` and ```${fileName}``` 
**AND** 
```${ROOT_OF_EXT}/out/providers/TerminalProvider.js:13:44``` around ```${rootPath.uri.fsPath}```

**Comment by LoveSponge** [comment]
The way node works dictates being able to specify the path using the `path` module and it will create it correctly for whichever operating system it is running.

[see docs](https://nodejs.org/dist/latest-v8.x/docs/api/path.html#path_path_win32)

@tcov189 Can you confirm this applies here?

It should be possible to use node path to build the path from the start, so it could be set once and implemented across all of these files. Which should mitigate a problem like this recurring in the future.

**Comment by tcov189** [comment]
@LoveSponge That is how I always thought it worked as well, but I think the issue is with the bash shell itself. If I change my default terminal to PowerShell or CMD then I don't have this issue. But using bash, it's combing every part of the path into one string.

**Comment by LoveSponge** [comment]
@tcov189 Sorry for the late response.
I have been using this **fsPath** _fix_ on my work (windows) PC for the last couple of days, and it has been working fine between restarts.

Since this is a windows file path issue thread i'm going to submit a pull request claiming a fix for this.

As a sidenote: I have also tested this on my home laptop (arch linux with gnome desktop) and have had good results.

Could you please provide more debugging information on your findings as i'm unable to reproduce.

**Comment by LoveSponge** [comment]
I have re-read this thread and realised that this issue requires the user to be using git bash on a windows machine.

After replicating this, i am now seeing the bug. While the above fix DOES fix an issue i was having just by using powershell on a windows machine and bash on a linux machine (as node correctly determines separators between linux and windows OS's as expected.)

I am looking for a fix for this as we speak. Currently i have managed to pin down the problem being that the path is trying to resolve with the wrong separators.

However with my fix you should be able to run this extension as normal on both operating systems, however on windows, only using powershell or CMD prompt.

@tcov189 

## UPDATE:
It looks like nodejs was never actually intended to support such an environment, my guess is because it would cause exactly a problem such as this (where node reads the OS and determines path, but doesn't cater for the possibility that an OS will be using it's contrary path structure.)

My suggestion to work around this would be to actually _install_ nodejs under CYGWIN, and point your PATH envs toward that instead of using a windows install.

Unfortunately, there doesn't seem to be a way to _detect_ whether the specific terminal environment is one of bash or other, otherwise this could be very easily patched. I could be wrong about this, though.

**Comment by ido-ran** [comment]
I've changed the function according to the description of https://github.com/g3offrey/javascript-test-runner/issues/7#issuecomment-408186810 and it solved the problem.

My tests are written in TypeScript and that does not works but at least the test runner is found.

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080
