### ISSUE TITLE
Cannot use when package.json/node_modules/jest is not at the workspace root

### ISSUE THREAD

**Issue by dantman** [g3offrey/javascript-test-runner#9]
I work on a project using Jest where `package.json` and `node_modules` are located at `src/main/webapp/` instead of the root.

Would you be willing to at least offer a config option to configure the path to the "JS root" or the path to the test runner.

Or better yet, would you be willing to just make things work automatically? By that I mean start at the current file's folder and walk upwards until you find the test runner (package.json with `jest` key, `jest.config.js`, or the equivalent for mocha).

**Comment by g3offrey** [comment]
Hi @dantman 
thank you very much for your contribution 👍 

You totally right, I wasn't aware of this use case while developing the extension 😩 
I think having a configuration option for the path of the test runner could be a good first solution.
The automatic one is obviously better but could be harder and longer to implement 😅 

In any case I add your propositions to my roadmap and I'll implement one the two as soon as possible. 😄

**Comment by cazfletch** [comment]
Hi @g3offrey any details on when this might be implemented? i would like it to work automatically too.

**Comment by g3offrey** [comment]
Hi @caroline-church 
please accept my apologies, as I'm not very active on this development. I don't have as much time as I want to attribute to open source even if I like contributing a lot 😞 

I'll try my possible to get back on this project as soon as possible and develop the requested features. I would also love to welcome new contributors / maintainers to keep it active (and build a real pipeline to ease deployment of new versions). 
So if you are interested don't hesitate to contact me. 😄

**Comment by roggenbrot** [comment]
Isn't this solved with #15?

**Comment by g3offrey** [comment]
I think @dantman issue is about a folder structure like that : 
````
root 
L src
  L main
    L webapp
      L node_modules
      L test.spec.js
````

If we run a test in _*test.spec.js*_ it will try to run Jest from *root/node_modules* instead of webapp as the opened folder is root (in Code).
I think we still have this issue. I'll investigate on this.

**Comment by roggenbrot** [comment]
You can add folder webapp as additional folder to the workspace 

https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by dantman** [comment]
@roggenbrot That breaks other extensions that need the various other config that is at the real repository root.

**Comment by roggenbrot** [comment]
@dantman 

Is this a guess or have you tried?

In multi root workspaces you can have multiple configs, one for the workspace (main folder) and additional, independent configs for  each sub root folder.

Configs will be retrieved from sub root folder, if not present it will fall back to the workspace config. 

So everything should work without problems.

If it's not working for a extension you should open a issue for that extension since they didn't  updated the extension according to the guide that was released as vs code introduced multi root workspace:

https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs

PR of #22  introduces the possibility to set the path of the jest binary and package.json that is used to detect test framework in the future.

I don't think that a automatic detection will make sense since it will break multi root workspaces.

What should the extension do if there are multiple package.json/jest files in the folder structure?

**Comment by dantman** [comment]
@roggenbrot The official Jest extension pops up error messages and the integrated terminal fails to launch bash. And I don't at all expect anyone to support this kind of config. Having a workspace where two of the roots refer to the same files at different levels is absurd. All the stuff that automatically runs per-workspace-folder would run twice over the same code.

#24 does sound like it may work for configuring the extension for my case.

> I don't think that a automatic detection will make sense since it will break multi root workspaces.
> 
> What should the extension do if there are multiple package.json/jest files in the folder structure?

Pretty much the same as other per-file extensions and cli tools. Start from the file/directory and walk upwards till you hit valid config or the workspace root.

- If the project is a monorepo with per-package jest/mocha and you start from `packages/foo/tests/foo.js` you'll hit `packages/foo/package.json` and find config there.
- If the monorepo instead has jest at the root, you'll hit `packages/foo/package.json`, won't find jest or mocha config there, then keep walking and find config when you hit `<rootdir>/package.json`.

**Comment by roggenbrot** [comment]
@dantman 

> Pretty much the same as other per-file extensions and cli tools. 

Which extensions? Maybe the functionallity can be copied from there

> Start from the file/directory and walk upwards till you hit valid config or the workspace root.

Again, this works just for you use case.  And what about the following structure:

- ROOT
   package.json
   +---CORE
         package.json
         +--node_modules
              jest
   +---CLIENT
         package.json
         +--node_modules
              jest
   +---SERVER
         package.json
         +--node_modules
               jest

How do `other per-file extensions and cli tools` handle this case?

>The official Jest extension pops up error messages and the integrated terminal fails to launch bash. 

No multi root support, you should create a ticket.

>And I don't at all expect anyone to support this kind of config

From the offical vs code documenation

>A multi-root workspace is a new way how to work with VS Code. At its core, it allows to open multiple folders in the same instance from any location that is accessible on disk. All parts of the VS Code user interface adapt to the number of folders opened, e.g. the file explorer will show all folders in a single tree and the full text search will search across all folders. It is in the best interest for the users that extensions also adapt to supporting multiple folders.

> Having a workspace where two of the roots refer to the same files at different levels is absurd. All the stuff that automatically runs per-workspace-folder would run twice over the same code.

I don't think you have read the documentation or any link i've posted you. 

Nothing will run twice but it's up to you how you structure your projects. Everyone is free to do whatever he wants. For one it's absurd, for others it's common practice.

**Comment by g3offrey** [comment]
I think the configuration added in #24 will resolve this issue. 👍 

The automatic resolution is a bit complex for the moment. 
I don't think this is worth it for the moment. However this can change in the future. 😅

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080
